output_folder: checkpoint

train:
  batch_size: 256
  epochs: 500
  patience: 30
  dropout: 0.5
  learning_rate: 0.00001
  weight_decay: 0.0001
  use_CLIP: true
  fast_training_for_test: false
  dataset: mushroom
  # dataset: fertilizer